# Import packages 

In [149]:
import cv2 as cv 
import numpy as np

# Draw an image

In [150]:
img = np.zeros((600, 600, 3), dtype=np.uint8)


# Draw the background ( sky & grass)

In [151]:
#background 
# width height color -1 for filled
cv.rectangle(img, (0, 0), (600, 400), (255, 255, 85), -1)
cv.rectangle(img, (0, 400), (600 ,600), (70, 180, 70), -1)


array([[[255, 255,  85],
        [255, 255,  85],
        [255, 255,  85],
        ...,
        [255, 255,  85],
        [255, 255,  85],
        [255, 255,  85]],

       [[255, 255,  85],
        [255, 255,  85],
        [255, 255,  85],
        ...,
        [255, 255,  85],
        [255, 255,  85],
        [255, 255,  85]],

       [[255, 255,  85],
        [255, 255,  85],
        [255, 255,  85],
        ...,
        [255, 255,  85],
        [255, 255,  85],
        [255, 255,  85]],

       ...,

       [[ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70],
        ...,
        [ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70]],

       [[ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70],
        ...,
        [ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70]],

       [[ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70],
        ...,
        [ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70]]

# Draw the Sun 

In [152]:
# center circle , radius, color, thickness
cv.circle(img, (75, 75), 50, (0,255,255), -1)
cv.circle(img, (75, 75), 53, (25,123,255),6)


array([[[255, 255,  85],
        [255, 255,  85],
        [255, 255,  85],
        ...,
        [255, 255,  85],
        [255, 255,  85],
        [255, 255,  85]],

       [[255, 255,  85],
        [255, 255,  85],
        [255, 255,  85],
        ...,
        [255, 255,  85],
        [255, 255,  85],
        [255, 255,  85]],

       [[255, 255,  85],
        [255, 255,  85],
        [255, 255,  85],
        ...,
        [255, 255,  85],
        [255, 255,  85],
        [255, 255,  85]],

       ...,

       [[ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70],
        ...,
        [ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70]],

       [[ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70],
        ...,
        [ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70]],

       [[ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70],
        ...,
        [ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70]]

# Draw the Tree

In [153]:
cv.line(img, (400, 480), (400,550), (30, 65, 155),15)

        

array([[[255, 255,  85],
        [255, 255,  85],
        [255, 255,  85],
        ...,
        [255, 255,  85],
        [255, 255,  85],
        [255, 255,  85]],

       [[255, 255,  85],
        [255, 255,  85],
        [255, 255,  85],
        ...,
        [255, 255,  85],
        [255, 255,  85],
        [255, 255,  85]],

       [[255, 255,  85],
        [255, 255,  85],
        [255, 255,  85],
        ...,
        [255, 255,  85],
        [255, 255,  85],
        [255, 255,  85]],

       ...,

       [[ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70],
        ...,
        [ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70]],

       [[ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70],
        ...,
        [ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70]],

       [[ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70],
        ...,
        [ 70, 180,  70],
        [ 70, 180,  70],
        [ 70, 180,  70]]

# Draw the leaf

In [154]:
triangle = np.array([
    [400, 380],  # رأس المثلث (أعلى)
    [360, 480],  # يسار القاعدة
    [440, 480]   # يمين القاعدة
], np.int32)

cv.fillPoly(img, [triangle], (75,168,70))
cv.imshow('image', img)
cv.waitKey(0)
cv.destroyAllWindows()

# Draw another Tree 

In [155]:
cv.line(img, (350, 480), (350,550), (30, 65, 155),15)
triangle2 = np.array([
    [350, 380],  # رأس المثلث (أعلى)
    [310, 480],  # يسار القاعدة
    [390, 480]   # يمين القاعدة
])
cv.fillPoly(img ,[triangle2], (75,168,70))
cv.imshow('image', img)
cv.waitKey(0)
cv.destroyAllWindows()

# write text on the Image


In [156]:
font = cv.FONT_HERSHEY_SIMPLEX
cv.putText(img, 'Drawn by Razan', (80, 400), font, 1, (200,255,200), 3
           , cv.LINE_AA)
cv.imshow('image', img)
cv.waitKey(0)
cv.destroyAllWindows()